### ISSUE TITLE
Encoding problem & 2 typo's

### ISSUE THREAD

**Issue by tvjon** [6by9/mmal_render_example#1]
I've tried several different image encodings hoping to display a YUYV (yuv4:2:2) frame via openmax, but no joy, so I'm trying your mmal render code, but again, whatever encoding I try never looks correct.

It's strange, because, for example the encoding I initially tried,

MMAL_ENCODING_YUYV

works just fine when I convert the same 600k yuyv frame to jpeg via mmal.

BTW,

presumably 2 typo's in:

        param.set |= MMAL_DISPLAY_SET_ALPHA;
        param.layer = 0;    //0 = opaque, 255 = transparent IIRC
        
should be 
        
        param.alpha = 255;    //255 = opaque, 0 = transparent

**Comment by 6by9** [comment]
The YUYV family of image formats is not supported by the display hardware. Video_render will reject it on mmal_port_format_commit / OMX_SetParameter(PortDefinition).

Input and output ports on all components should report their supported formats via ```MMAL_PARAMETER_SUPPORTED_ENCODINGS```
[```mmal_util_rgb_order_fixed```](https://github.com/raspberrypi/userland/blob/master/interface/mmal/util/mmal_util.c#L437) is an example of retrieving it as it changed when the camera component was fixed for RGB24/BGR24 being swapped. As you can see there, it passes in storage for 25 encodings. I don't think any component exceeds that yet, but MMAL handles that anyway by filling what you provide and returning MMAL_ENOSPC with the header size set to the required size for the complete list.

I'm not fussed over the typos. This was written as someone asked for a quick example of how to render an image.

**Comment by tvjon** [comment]
MMAL_PARAMETER_SUPPORTED_ENCODINGS is very handy, thank you.

I received:

mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x17809a0 (EINVAL)

after checking.

So I suppose the encoding works fine when converting to jpeg as no display hardware is involved.

Ok, I'll think about this. It's for a rpi1 project, & there's no NEON available to do the yuv422 packed to yuv420.


Oh. It's just that people may be perplexed after building & running it as nothing will be visible on screen, unless that line is changed.

**Comment by 6by9** [comment]
There is an IL equivalent to MMAL_PARAMETER_SUPPORTED_ENCODINGS. IIRC it's OMX_IndexParamVideoPortFormat, but you have to call repeatedly incrementing nIndex each time until you get OMX_ErrorNoMore back.

I can't remember what formats are supported on the input of image_encode. YUYV is plausible, although it will include a software repack into YUV422 planar for the JPEG hardware (pretty efficient to do on the VPU, but does hit memory bandwidth).

You can use "vc.ril.isp" to convert from YUYV to a more usable format. You can resize to two different output resolutions as well should you need.

**Comment by 6by9** [comment]
Typo fixed, which I think resolves the main issue.
The question on YUYV has been answered.

Happy to close? I'll close Monday 5th Nov if no response.

**Comment by tvjon** [comment]
Yes, that's fine, & thank you for your couple of suggestions as to alternative approaches.

Based on those approaches, I'll raise an issue in another topic, as I'm getting errors.
