### ISSUE TITLE
32 bits per pixel

### ISSUE THREAD

**Issue by ktb92677** [6by9/mmal_render_example#2]
Hi! Setting the following: #define ENCODING    MMAL_ENCODING_RGB32
 makes the program return the following error:

mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0xc42da0 (EINVAL)

This error shows on all pixel formats that are 32 bits per pixel

**Comment by 6by9** [comment]
Check the supported formats using ```MMAL_PARAMETER_SUPPORTED_ENCODINGS```.

I've just pushed changes that dump that out before starting. The supported 4CC's are
```
0: I420
1: I42S
2: YV12
3: NV12
4: NV21
5: I422
6: I422
7: SAND
8: RGB2
9: RGB3
10: BGR3
11: BGRA
12: RGBA
```
Note RGBA and BGRA, not RGB32/BGR32 which are the no-alpha versions.

**Comment by ktb92677** [comment]
Okay thanks, this worked. This issue can be closed out.
