### ISSUE TITLE
Quick way to clear out buffer

### ISSUE THREAD

**Issue by ktb92677** [6by9/mmal_render_example#3]
Hi! Is there anyway to quickly zero out a buffer? For my 32bpp buffer for a 1920x1080 screen I am finding that it is taking anywhere from 9 to 15 ms to actually zero out the buffer using memset on a raspberry PI. Thanks for the help!

**Comment by ktb92677** [comment]
@6by9 bump

**Comment by 6by9** [comment]
Nothing particular that I'm aware of.
You could use DMA if you wanted.
